### ISSUE TITLE
ENCHANCEMENT - FAQ explanation on which server to pick :-) 

### ISSUE THREAD

**Issue by floristotle** [muppet3000/homeassistant-growatt_server_api#27]
**Is your feature request related to a problem? Please describe.**
I do not know which server setting to pick. I know server.growat works, but I am for example uncertain if there is a more stable option.

**Describe the solution you'd like**
I'd love a small explanation on which server is for what.

**Describe alternatives you've considered**
I've browsed issues of this and the official HA plugin, but it takes a while to find good information.

**Comment by muppet3000** [comment]
Hi @floristotle - The server to choose is dependent on what version of the website you go to and are able to log in to.

If you use `server.growatt.com` you can use either `server.growatt.com` or `server-api.growatt.com`. I had removed `server.growatt.com` some time ago because Growatt stopped supporting it, but it started working again so I re-added it as another option when Growatt started changing everything the other day and breaking things.

It's totally up to you which one you use out of the options that are available, they will both return the same information as the data eventually comes from the same endpoint.

**Comment by Saentist** [comment]
All of them point to same CDN but on different input nodes.

**Comment by muppet3000** [comment]
Closing as this isn't an issue and there was never any further feedback, plus, I'm trying to steer everyone towards grott.
